version: '3'

services:
  postgres:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
  app:
    build: .
    env_file:
      - .env

volumes:
  postgres-data:
