version: '3'

services:
  postgres:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB']
      interval: 5s
      timeout: 2s
      retries: 5
    networks:
      - dokploy-network
  app:
    image: codeitninja/loghog:latest
    depends_on:
      - postgres
    environment:
      - PUBLIC_SOCKET_URL
      - DATABASE_URL
    networks:
      - dokploy-network
volumes:
  postgres-data:

networks:
  dokploy-network:
    external: true
